### ISSUE TITLE
i got some errors

### ISSUE THREAD

**Issue by Mehran** [utiso/dorkbot#1]
```
./dorkbot.py -i google -o engine=012345678901234567891:abc12defg3h,query="filetype:php inurl:id" -s arachni
Traceback (most recent call last):
  File "./dorkbot.py", line 174, in <module>
    main()
  File "./dorkbot.py", line 69, in main
    index(db, args.indexer, args.indexer_options)
  File "./dorkbot.py", line 126, in index
    results = indexer_module.run(options)
  File "/root/Desktop/git/dorkbot/indexers/google.py", line 31, in run
    results = get_results(phantomjs_path, options["engine"], options["query"], domain)
  File "/root/Desktop/git/dorkbot/indexers/google.py", line 46, in get_results
    output = subprocess.check_output(index_cmd)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by rickycoolige** [comment]
HI, 
I am getting same errors.. Did you ever Resolve??
THX

robot:~/dorkbot# ./dorkbot.py -i google -o engine=0099604576279661038117:vquegqft89g,query=filetype:php -s arachni
Traceback (most recent call last):
  File "./dorkbot.py", line 177, in <module>
    main()
  File "./dorkbot.py", line 69, in main
    index(db, args.indexer, args.indexer_options)
  File "./dorkbot.py", line 129, in index
    results = indexer_module.run(options)
  File "/root/dorkbot/indexers/google.py", line 46, in run
    return results
UnboundLocalError: local variable 'results' referenced before assignment
robot:~/dorkbot# ^C
