### ISSUE TITLE
two errors

### ISSUE THREAD

**Issue by littleheary** [utiso/dorkbot#13]
1、when  i run google，this need photomjs，but have error
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
2020-01-11T19:41:09-0500 - ERROR - Failed to execute phantomjs command
Traceback (most recent call last):
  File "dorkbot.py", line 674, in <module>
    main()
  File "dorkbot.py", line 69, in main
    index(db, blacklist, load_module("indexers", args.indexer), args, indexer_options)
  File "dorkbot.py", line 194, in index
    for url in urls:
TypeError: 'bool' object is not iterable

2、when i run google-api，also have error
Traceback (most recent call last):
  File "dorkbot.py", line 674, in <module>
    main()
  File "dorkbot.py", line 69, in main
    index(db, blacklist, load_module("indexers", args.indexer), args, indexer_options)
  File "dorkbot.py", line 195, in index
    if not blacklist.match(Target(url)): targets.append(url)
  File "dorkbot.py", line 466, in __init__
    self.starttime = generate_timestamp()
  File "dorkbot.py", line 291, in generate_timestamp
    return datetime.datetime.now().astimezone().isoformat()
ValueError: astimezone() cannot be applied to a naive datetime

how can i run this success？

**Comment by jgor** [comment]
Apologies for the late reply, just noticed this. If you're still getting these errors can you post the command you're using and I'll try to re-produce it?
